version: '3'

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - scraper_api

  scraper_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "scraper_api-1"
    command: gunicorn scrapper.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    volumes:
      - ./:/app
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'scrapper'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

volumes:
  mysql_data: